name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC every day

jobs:
  create-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create daily commit (22f3001315@ds.study.iitm.ac.in)
        run: |
          echo "Daily update $(date)" >> daily-update.txt
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add daily-update.txt
          git commit -m "Daily automated commit"
          git push
